version: '3.8'

services:
  app:
    image: dvcoronado/practica3:1.0.0
    ports:
      - "8443:8443"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/appdb
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=apppassword
    volumes:
      - ./certs:/etc/ssl/certs:ro  # Si usas certificados personalizados

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
